<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="BERD AI Pilot (GitHub Copilot)">
<meta name="description" content="Documents how the synthetic dataset for CRP 241 exercises was constructed, where each parameter came from, and what was approximated.">

<title>Appendix B — Simulation Process and Assumptions: IVAM-ED Synthetic Dataset – IVAM-ED: A CRP 241 Teaching Case</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./simulation-refinements.html" rel="next">
<link href="./R/A1-answer-key.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f265b87640d31df99b0219922ff83384.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./R/A1-answer-key.html">Appendices</a></li><li class="breadcrumb-item"><a href="./simulation-assumptions.html"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simulation Process and Assumptions: IVAM-ED Synthetic Dataset</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">IVAM-ED: A CRP 241 Teaching Case</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/scgrambow/berd-template-field-test-01" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Analysis Modules</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/01-data-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Module 1: Data Setup and Inspection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/02-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Module 2: Descriptive Statistics and Baseline Characteristics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/03-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Module 3: Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/04-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Module 4: Estimation and Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/05-ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Module 5: Linear Regression and ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/06-missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Module 6: Missing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/07-interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Module 7: Interpretation and Critical Appraisal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/08-capstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Module 8: Capstone — Write a Methods and Results Section</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R/A1-answer-key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Answer Key</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulation-assumptions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simulation Process and Assumptions: IVAM-ED Synthetic Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulation-refinements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simulation Refinements: Debugging and Iteration Log</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./critical-appraisal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Critical Appraisal: A Reviewer’s Assessment of the IVAM-ED Trial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">References and Source Documents</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pedagogical-essay.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Building a Teaching Repository with AI Assistance: A Process Essay</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#simulation-process-and-assumptions" id="toc-simulation-process-and-assumptions" class="nav-link active" data-scroll-target="#simulation-process-and-assumptions">Simulation Process and Assumptions</a>
  <ul class="collapse">
  <li><a href="#what-is-a-synthetic-dataset" id="toc-what-is-a-synthetic-dataset" class="nav-link" data-scroll-target="#what-is-a-synthetic-dataset"><span class="header-section-number">B.1</span> What Is a Synthetic Dataset?</a></li>
  <li><a href="#primary-sources" id="toc-primary-sources" class="nav-link" data-scroll-target="#primary-sources"><span class="header-section-number">B.2</span> Primary Sources</a></li>
  <li><a href="#simulation-strategy-moment-matching" id="toc-simulation-strategy-moment-matching" class="nav-link" data-scroll-target="#simulation-strategy-moment-matching"><span class="header-section-number">B.3</span> Simulation Strategy: Moment Matching</a></li>
  <li><a href="#parameter-table" id="toc-parameter-table" class="nav-link" data-scroll-target="#parameter-table"><span class="header-section-number">B.4</span> Parameter Table</a>
  <ul class="collapse">
  <li><a href="#demographics" id="toc-demographics" class="nav-link" data-scroll-target="#demographics"><span class="header-section-number">B.4.1</span> Demographics</a></li>
  <li><a href="#baseline-clinical-measures" id="toc-baseline-clinical-measures" class="nav-link" data-scroll-target="#baseline-clinical-measures"><span class="header-section-number">B.4.2</span> Baseline Clinical Measures</a></li>
  <li><a href="#follow-up-outcome-model" id="toc-follow-up-outcome-model" class="nav-link" data-scroll-target="#follow-up-outcome-model"><span class="header-section-number">B.4.3</span> Follow-Up Outcome Model</a></li>
  <li><a href="#missingness" id="toc-missingness" class="nav-link" data-scroll-target="#missingness"><span class="header-section-number">B.4.4</span> Missingness</a></li>
  </ul></li>
  <li><a href="#known-approximations-and-limitations" id="toc-known-approximations-and-limitations" class="nav-link" data-scroll-target="#known-approximations-and-limitations"><span class="header-section-number">B.5</span> Known Approximations and Limitations</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility"><span class="header-section-number">B.6</span> Reproducibility</a></li>
  <li><a href="#how-to-cite-the-source-publications" id="toc-how-to-cite-the-source-publications" class="nav-link" data-scroll-target="#how-to-cite-the-source-publications"><span class="header-section-number">B.7</span> How to Cite the Source Publications</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/scgrambow/berd-template-field-test-01/edit/main/simulation-assumptions.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/scgrambow/berd-template-field-test-01/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./R/A1-answer-key.html">Appendices</a></li><li class="breadcrumb-item"><a href="./simulation-assumptions.html"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simulation Process and Assumptions: IVAM-ED Synthetic Dataset</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Appendix B — Simulation Process and Assumptions: IVAM-ED Synthetic Dataset</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>BERD AI Pilot (GitHub Copilot) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="simulation-process-and-assumptions" class="level1 unnumbered">
<h1 class="unnumbered">Simulation Process and Assumptions</h1>
<p>This document explains how the synthetic dataset in <code>R/simulate-ivam-ed.R</code> was built, where every number came from, and what the known limitations are. It is written for instructors and students who want to understand the data before analyzing it.</p>
<section id="what-is-a-synthetic-dataset" class="level2" data-number="B.1">
<h2 data-number="B.1" class="anchored" data-anchor-id="what-is-a-synthetic-dataset"><span class="header-section-number">B.1</span> What Is a Synthetic Dataset?</h2>
<p>A synthetic dataset is a computer-generated dataset whose statistical properties (sample size, means, standard deviations, correlations, treatment effects) are designed to closely resemble those of a real study — but it contains no real participant data. Every row represents a fictional person whose values were drawn from probability distributions, not measured from an actual patient.</p>
<p><strong>Why use a synthetic dataset?</strong></p>
<ul>
<li>The real IVAM-ED trial data are not publicly available. Using synthetic data lets us analyze a realistic dataset without exposing real participants.</li>
<li>Synthetic data can be regenerated reproducibly from a fixed random seed, so every student starts from the same dataset.</li>
<li>Because the data are not real, students can explore, make mistakes, and re-run analyses freely without any risk of PHI exposure.</li>
</ul>
<p><strong>What the synthetic dataset is NOT:</strong></p>
<ul>
<li>It is not a reconstruction of the real data. We do not have individual-level data and have not attempted to reverse-engineer them.</li>
<li>It will not reproduce the exact p-values or confidence intervals from the paper in every run. The published results came from the real data; our simulation approximates the aggregate-level statistics.</li>
<li>Variables that appear continuous (e.g., SRQ-20, MMSE) may have slightly different distributions than the real data because we used normal distributions as approximations.</li>
</ul>
<hr>
</section>
<section id="primary-sources" class="level2" data-number="B.2">
<h2 data-number="B.2" class="anchored" data-anchor-id="primary-sources"><span class="header-section-number">B.2</span> Primary Sources</h2>
<p>Every parameter used in the simulation comes from one of three published sources:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Citation</th>
<th>Role in simulation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Results paper</td>
<td>Matzenbacher et al.&nbsp;(2026). <em>JAMA Network Open</em>, 9(1):e2553508. DOI: 10.1001/jamanetworkopen.2025.53508</td>
<td>Baseline demographics (Table 1), follow-up outcome means (Table 2), subgroup counts (Figure 2), missingness (Results text)</td>
</tr>
<tr class="even">
<td>Protocol and SAP</td>
<td>Da Costa et al.&nbsp;(2024). <em>Trials</em>, 25(1):205. DOI: 10.1186/s13063-024-08055-3</td>
<td>Instrument ranges, sample size calculation, effect size (0.68), power (90%), dropout assumption (20%), analysis model specification</td>
</tr>
<tr class="odd">
<td>JAMA Supplement 1</td>
<td>Matzenbacher et al.&nbsp;(2026), Supplement 1 — Study Protocol and SAP embedded in results paper</td>
<td>Subgroup definitions, MMSE cognitive-decline cutoffs, randomization procedure</td>
</tr>
</tbody>
</table>
<p>Extracted Markdown versions of all three are in <code>source/extracted/</code>.</p>
<hr>
</section>
<section id="simulation-strategy-moment-matching" class="level2" data-number="B.3">
<h2 data-number="B.3" class="anchored" data-anchor-id="simulation-strategy-moment-matching"><span class="header-section-number">B.3</span> Simulation Strategy: Moment Matching</h2>
<p>We used <strong>moment matching</strong>: for each variable, we chose a probability distribution whose mean and standard deviation match the published values.</p>
<p>This is the simplest defensible approach when you have only summary statistics (means and SDs) and no access to individual-level data. It does not attempt to match skewness, kurtosis, or inter-variable correlations exactly, but it produces a dataset that “looks right” at the summary level — which is the goal for a teaching exercise.</p>
<p>An alternative approach would be to use a multivariate normal distribution (<code>MASS::mvrnorm</code>) to generate all outcomes simultaneously with a plausible correlation structure. That approach is more realistic but adds complexity that obscures the teaching purpose. Instructors who want to extend the simulation to include realistic inter-variable correlations can modify the script using the correlation structure described in the “Known Approximations” section below.</p>
<hr>
</section>
<section id="parameter-table" class="level2" data-number="B.4">
<h2 data-number="B.4" class="anchored" data-anchor-id="parameter-table"><span class="header-section-number">B.4</span> Parameter Table</h2>
<p>This table documents every simulation parameter, its value, and its source. “Pooled” means we averaged across the two published group-specific values.</p>
<section id="demographics" class="level3" data-number="B.4.1">
<h3 data-number="B.4.1" class="anchored" data-anchor-id="demographics"><span class="header-section-number">B.4.1</span> Demographics</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Distribution</th>
<th>Parameters</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N</td>
<td>fixed</td>
<td>112 total (56 per group)</td>
<td>Methods; Figure 1</td>
</tr>
<tr class="even">
<td><code>group</code></td>
<td>Bernoulli</td>
<td>p = 0.50 (1:1, simple random)</td>
<td>Methods: “randomly assigned in a 1:1 ratio using a computer-generated simple random sequence without stratification or blocking”</td>
</tr>
<tr class="odd">
<td><code>age</code></td>
<td>Normal, clipped ≥ 65</td>
<td>µ = 72.5, σ = 5.7</td>
<td>Results abstract; Table 1: ctrl 72.4 (6.0), int 72.6 (5.4)</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Bernoulli</td>
<td>p = 0.634</td>
<td>Results: “71 females [63.4%]”</td>
</tr>
<tr class="odd">
<td><code>edu_years</code></td>
<td>Normal, clipped ≥ 0</td>
<td>µ = 6.95, σ = 4.05</td>
<td>Table 1: ctrl 7.5 (3.9) years, int 6.4 (4.2) years; pooled</td>
</tr>
<tr class="even">
<td><code>income_wages</code></td>
<td>Normal, clipped ≥ 0.5</td>
<td>µ = 2.30, σ = 2.40</td>
<td>Results text: “mean (SD) individual income was 2.3 (2.4) Brazilian minimum wages”</td>
</tr>
<tr class="odd">
<td><code>dm_duration_y</code></td>
<td>Normal, clipped ≥ 1</td>
<td>µ = 16.9, σ = 11.6</td>
<td>Results text: “mean (SD) duration of diabetes was 16.9 (11.6) years”</td>
</tr>
<tr class="even">
<td><code>insulin</code></td>
<td>Bernoulli</td>
<td>p = 0.536</td>
<td>Figure 2 subgroup: “60 (53.6%) Yes” insulin use; Table 1: ctrl 28/56 (50.0%), int 32/56 (57.1%)</td>
</tr>
<tr class="odd">
<td><code>hx_depression</code></td>
<td>Bernoulli</td>
<td>p = 0.357</td>
<td>Figure 2 subgroup: “40 (35.7%) Yes” history of depression</td>
</tr>
<tr class="even">
<td><code>hx_anxiety</code></td>
<td>Bernoulli</td>
<td>p = 0.339</td>
<td>Figure 2 subgroup: “38 (32.9%) [actually 33.9%]” history of anxiety; used 38/112 = 0.339</td>
</tr>
</tbody>
</table>
</section>
<section id="baseline-clinical-measures" class="level3" data-number="B.4.2">
<h3 data-number="B.4.2" class="anchored" data-anchor-id="baseline-clinical-measures"><span class="header-section-number">B.4.2</span> Baseline Clinical Measures</h3>
<p>These instruments were measured at the baseline visit (week −1).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Distribution</th>
<th>Parameters</th>
<th>Bounds</th>
<th>Instrument description</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mmse_0</code></td>
<td>Normal, bounded</td>
<td>µ = 24.15, σ = 4.25</td>
<td>[0, 30]</td>
<td>Mini-Mental State Examination. Higher = better cognitive function.</td>
<td>Table 1: ctrl 24.8 (4.0), int 23.5 (4.5)</td>
</tr>
<tr class="even">
<td><code>srq20_0</code></td>
<td>Normal, bounded, rounded</td>
<td>µ = 7.45, σ = 5.00</td>
<td>[0, 20]</td>
<td>Self-Reporting Questionnaire-20. Higher = greater mental distress.</td>
<td>Table 1: ctrl 7.0 (4.7), int 7.9 (5.2)</td>
</tr>
<tr class="odd">
<td><code>sci_r_0</code></td>
<td>Normal, bounded</td>
<td>µ = 35.85, σ = 6.40</td>
<td>[0, 56]</td>
<td>Self-Care Inventory Revised. Higher = better diabetes self-care adherence.</td>
<td>Table 1: ctrl 36.5 (5.9), int 35.2 (6.8)</td>
</tr>
<tr class="even">
<td><code>pss_0</code></td>
<td>Normal, bounded</td>
<td>µ = 22.10, σ = 10.35</td>
<td>[0, 40]</td>
<td>Perceived Stress Scale. Higher = greater perceived stress.</td>
<td>Table 1: ctrl 23.6 (10.3), int 20.6 (10.3)</td>
</tr>
<tr class="odd">
<td><code>sf36_0</code></td>
<td>Normal, bounded</td>
<td>µ = 50.55, σ = 21.85</td>
<td>[0, 100]</td>
<td>SF-36 quality of life. Higher = better quality of life.</td>
<td>Table 1: ctrl 50.2 (21.5), int 50.9 (22.2)</td>
</tr>
<tr class="even">
<td><code>hba1c_0</code></td>
<td>Normal, clipped</td>
<td>µ = 7.90, σ = 1.55</td>
<td>[≥ 4.5%]</td>
<td>HbA1c (%). Lower = better glycemic control.</td>
<td>Table 1: ctrl 7.8 (1.5), int 8.0 (1.6)</td>
</tr>
<tr class="odd">
<td><code>cognitive_decline</code></td>
<td>Derived</td>
<td>MMSE cutoff: &lt; 24 if edu &lt; 5 years; &lt; 26 otherwise</td>
<td>binary</td>
<td>Positive screening for cognitive decline.</td>
<td>Protocol/SAP: MMSE education-adjusted cutoffs; Figure 2: 72/112 (64.3%) positive</td>
</tr>
</tbody>
</table>
</section>
<section id="follow-up-outcome-model" class="level3" data-number="B.4.3">
<h3 data-number="B.4.3" class="anchored" data-anchor-id="follow-up-outcome-model"><span class="header-section-number">B.4.3</span> Follow-Up Outcome Model</h3>
<p>We used an <strong>ANCOVA-generating model</strong> for each follow-up outcome:</p>
<p><span class="math display">\[y_{12,i} = \alpha + \tau \cdot \text{group}_i + \beta \cdot y_{0,i} + \varepsilon_i\]</span></p>
<p>Where: - <span class="math inline">\(\alpha\)</span> = intercept calibrated so the control group mean matches the published baseline-adjusted mean at 12 weeks - <span class="math inline">\(\tau\)</span> = treatment effect (mean difference, intervention vs.&nbsp;control), taken directly from the published Table 2 baseline-adjusted estimates - <span class="math inline">\(\beta\)</span> = baseline-to-follow-up regression coefficient, set to <strong>0.70</strong> for all outcomes (see rationale below) - <span class="math inline">\(\varepsilon_i\)</span> = residual error, drawn from Normal(0, σ_ε)</p>
<section id="why-β-0.70" class="level4" data-number="B.4.3.1">
<h4 data-number="B.4.3.1" class="anchored" data-anchor-id="why-β-0.70"><span class="header-section-number">B.4.3.1</span> Why β = 0.70?</h4>
<p>The test-retest reliability (baseline-to-follow-up correlation) for psychological and clinical instruments over 12 weeks is typically in the 0.60–0.80 range. We chose 0.70 as a round central estimate. This value is not reported in the paper (individual-level correlations are never reported in aggregate publications). Using β = 0.70 reproduces the published standard errors and confidence interval widths reasonably well, confirming it is a plausible value.</p>
</section>
<section id="intercept-calibration" class="level4" data-number="B.4.3.2">
<h4 data-number="B.4.3.2" class="anchored" data-anchor-id="intercept-calibration"><span class="header-section-number">B.4.3.2</span> Intercept calibration</h4>
<p>For each outcome, we solve for <span class="math inline">\(\alpha\)</span> so that the expected control-group mean at follow-up matches the published adjusted mean:</p>
<p><span class="math display">\[\alpha = \bar{y}_{12,\text{ctrl}} - \beta \cdot \bar{y}_{0,\text{ctrl}}\]</span></p>
</section>
<section id="residual-standard-deviation" class="level4" data-number="B.4.3.3">
<h4 data-number="B.4.3.3" class="anchored" data-anchor-id="residual-standard-deviation"><span class="header-section-number">B.4.3.3</span> Residual standard deviation</h4>
<p>The residual SD (σ_ε) is calibrated so that the resulting SE of the treatment effect coefficient matches the published SE from Table 2. Specifically:</p>
<p><span class="math display">\[\text{SE}(\hat\tau) \approx \sigma_\varepsilon \sqrt{\frac{2}{n_\text{complete}}}\]</span></p>
<p>We solve for σ_ε using the published SE and n = 103 completers.</p>
</section>
<section id="follow-up-parameters-by-outcome" class="level4" data-number="B.4.3.4">
<h4 data-number="B.4.3.4" class="anchored" data-anchor-id="follow-up-parameters-by-outcome"><span class="header-section-number">B.4.3.4</span> Follow-up parameters by outcome</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>Published MD (τ) used</th>
<th>Model column actually used</th>
<th>Published SE</th>
<th>Target ctrl mean</th>
<th>Residual σ</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>srq20_12</code></td>
<td>−1.28</td>
<td>Baseline-adjusted</td>
<td>0.45 (baseline-adj)</td>
<td>7.66</td>
<td>~2.3</td>
<td>Table 2</td>
</tr>
<tr class="even">
<td><code>sf36_12</code></td>
<td>+9.46</td>
<td><strong>Fully adjusted</strong></td>
<td>2.95 (from CI width)</td>
<td>~49.0</td>
<td>~15.0</td>
<td>Table 3</td>
</tr>
<tr class="odd">
<td><code>sci_r_12</code></td>
<td>+3.40</td>
<td><strong>Fully adjusted</strong></td>
<td>0.91 (from CI width)</td>
<td>~36.0</td>
<td>~4.6</td>
<td>Table 3</td>
</tr>
<tr class="even">
<td><code>hba1c_12</code></td>
<td>−0.48</td>
<td><strong>Fully adjusted</strong></td>
<td>0.19 (from CI width)</td>
<td>~8.04</td>
<td>~0.97</td>
<td>Table 3</td>
</tr>
<tr class="odd">
<td><code>pss_12</code></td>
<td>−3.00</td>
<td><strong>Fully adjusted</strong></td>
<td>1.63 (from CI width)</td>
<td>~21.0</td>
<td>~8.3</td>
<td>Table 3</td>
</tr>
</tbody>
</table>
<p><strong>Correction (added on fidelity review):</strong> The intent, stated throughout this document and in <code>R/simulate-ivam-ed.R</code>’s comments, was to calibrate every τ to the <strong>baseline-adjusted</strong> column of Table 2/3 — the simpler model students fit first in Module 5 — and let the fully adjusted model be a later comparison. That was done correctly for the primary outcome (SRQ-20: τ = −1.28, the baseline-adjusted MD). For the four secondary outcomes, the τ actually coded into the script is the <strong>fully adjusted</strong> MD, not the baseline-adjusted MD (baseline-adjusted values are SF-36 +8.20, SCI-R +3.17, PSS −2.47, HbA1c −0.47 — all somewhat smaller in magnitude than what is coded). This was not caught during the original build-and-verify cycle described in <code>simulation-refinements.md</code> because that cycle only checked the primary outcome against its target. See Known Approximation 8 below and the <a href="./simulation-refinements.html">Simulation Fidelity Assessment</a> for the measured consequence: under <code>set.seed(241)</code>, this contributes to two secondary outcomes (SCI-R, PSS) not reproducing the published significance pattern when students fit the baseline-adjusted model taught in Module 5.</p>
<p>The synthetic data itself was <strong>not</strong> changed after this was found — doing so would silently invalidate every downstream module number, exercise answer, and the Answer Key, all of which were built against <code>set.seed(241)</code>’s actual output. Consistent with this repository’s transparency principle, the mismatch is documented here and in the Fidelity Assessment rather than quietly patched.</p>
</section>
</section>
<section id="missingness" class="level3" data-number="B.4.4">
<h3 data-number="B.4.4" class="anchored" data-anchor-id="missingness"><span class="header-section-number">B.4.4</span> Missingness</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total missing at 12 weeks</td>
<td>9 participants (8.0%)</td>
<td>Results: “103 participants (92.0%) completed the trial”</td>
</tr>
<tr class="even">
<td>Missing by group</td>
<td>5 control, 4 intervention</td>
<td>Inferred from completers: 52 intervention, 51 control</td>
</tr>
<tr class="odd">
<td>Reason for missingness</td>
<td>6 lost to follow-up, 3 deaths</td>
<td>Results text</td>
</tr>
<tr class="even">
<td>Missing data mechanism</td>
<td>Missing at random (MAR)</td>
<td>Protocol SAP: “frequency and reasons for missing data are expected to be missing at random”</td>
</tr>
<tr class="odd">
<td>MAR mechanism implemented</td>
<td>Higher baseline SRQ-20 slightly increases P(missing)</td>
<td>Clinically plausible; more distressed participants more likely to drop out</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="known-approximations-and-limitations" class="level2" data-number="B.5">
<h2 data-number="B.5" class="anchored" data-anchor-id="known-approximations-and-limitations"><span class="header-section-number">B.5</span> Known Approximations and Limitations</h2>
<ol type="1">
<li><p><strong>Normal approximations for bounded discrete variables.</strong> SRQ-20 (0–20, integer) and MMSE (0–30, integer) are discrete sum scores. We simulate them as continuous normals and round. This means the distribution may have values at the tails that are impossible in the real instrument; the <code>clamp()</code> step handles this.</p></li>
<li><p><strong>Independent baseline variables.</strong> We simulate each baseline variable independently (no inter-variable correlation). In the real data, SRQ-20 and PSS are likely positively correlated (~0.55), SRQ-20 and SF-36 negatively correlated (~−0.45), etc. This simplification is intentional to keep the script readable. It means that within-person patterns will not be as coherent as in real data. Instructors who want to explore this can add <code>MASS::mvrnorm()</code> for the outcome block.</p></li>
<li><p><strong>Single-site, Brazilian sample.</strong> The real study enrolled participants at one academic medical center in Brazil with low income and limited formal education. These characteristics are baked into the demographic parameters. The simulation is not intended to represent North American or European populations.</p></li>
<li><p><strong>Effect sizes are fixed, not sampled.</strong> The simulation produces a dataset where the true treatment effect equals the published MD. In a real trial, the observed effect in any single run will vary around the true effect due to sampling variability. This means running the script multiple times with different seeds will give different p-values, sometimes crossing the significance threshold.</p></li>
<li><p><strong>No group-level imbalance in baseline.</strong> The real randomization produced essentially balanced groups (Table 1 shows no meaningful differences). We enforce exact equal group sizes (56/56) and simulate from pooled baseline parameters, so our groups will also be balanced on average.</p></li>
<li><p><strong>No inter-rater reliability or measurement error modeling.</strong> The real outcomes were interviewer-assessed. We do not add a separate measurement-error component.</p></li>
<li><p><strong>Follow-up HbA1c bounding.</strong> HbA1c is clipped at 4.5% as a physiological lower bound. Very high values are theoretically unbounded but rare; the simulation will occasionally produce values above 12% that are implausible for a treated older adult with diabetes.</p></li>
<li><p><strong>Secondary-outcome τ calibrated to the wrong Table 2/3 column.</strong> SF-36, SCI-R, PSS, and HbA1c were calibrated to the <em>fully adjusted</em> published MD rather than the <em>baseline-adjusted</em> MD the simulation strategy calls for (SRQ-20 was calibrated correctly). Combined with ordinary single-seed sampling variability, this means two of the four secondary outcomes (SCI-R, PSS) do not reproduce the published significance conclusion when students fit the baseline-adjusted model in Module 5, under the fixed <code>set.seed(241)</code>. See the <a href="./simulation-refinements.html">Simulation Fidelity Assessment</a> for the full outcome-by-outcome numbers.</p></li>
</ol>
<hr>
</section>
<section id="reproducibility" class="level2" data-number="B.6">
<h2 data-number="B.6" class="anchored" data-anchor-id="reproducibility"><span class="header-section-number">B.6</span> Reproducibility</h2>
<p>The simulation uses <code>set.seed(241)</code> at the top of <code>R/simulate-ivam-ed.R</code>. The seed 241 refers to CRP 241, the course this dataset was built for.</p>
<p>Running the script with the same seed on R ≥ 4.6.1 will always produce the same dataset. If the script is run on a different R version, results may differ because R’s random number generator can change across major versions.</p>
<p>The R version and renv lockfile are recorded in <code>renv.lock</code>. To reproduce the exact environment: clone the repository, restore with <code>renv::restore()</code>, then source <code>R/simulate-ivam-ed.R</code>.</p>
<hr>
</section>
<section id="how-to-cite-the-source-publications" class="level2" data-number="B.7">
<h2 data-number="B.7" class="anchored" data-anchor-id="how-to-cite-the-source-publications"><span class="header-section-number">B.7</span> How to Cite the Source Publications</h2>
<p>Any work derived from this simulated dataset should acknowledge the original published trial. Suggested language for student reports:</p>
<blockquote class="blockquote">
<p>“Analysis was performed on a synthetic dataset constructed to approximate the sample characteristics reported in Matzenbacher et al.&nbsp;(2026). The synthetic data were generated for teaching purposes and do not represent individual participant data from the IVAM-ED trial.”</p>
</blockquote>
<p>Full citations:</p>
<ul>
<li><p>Matzenbacher LS, da Costa FL, de Barros LGB, et al.&nbsp;Interactive virtual assistant for health promotion among older adults with type 2 diabetes: the IVAM-ED randomized clinical trial. <em>JAMA Network Open</em>. 2026;9(1):e2553508. doi:10.1001/jamanetworkopen.2025.53508</p></li>
<li><p>Da Costa FL, Matzenbacher LS, Gheno V, et al.&nbsp;Interactive virtual assistance for mental health promotion and self-care management in elderly with type 2 diabetes (IVAM-ED): study protocol and statistical analysis plan for a randomized controlled trial. <em>Trials</em>. 2024;25(1):205. doi:10.1186/s13063-024-08055-3</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/scgrambow\.github\.io\/berd-template-field-test-01\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./R/A1-answer-key.html" class="pagination-link" aria-label="Answer Key">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Answer Key</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./simulation-refinements.html" class="pagination-link" aria-label="Simulation Refinements: Debugging and Iteration Log">
        <span class="nav-page-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simulation Refinements: Debugging and Iteration Log</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/scgrambow/berd-template-field-test-01/edit/main/simulation-assumptions.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/scgrambow/berd-template-field-test-01/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>